title: RecipeCleaner
description:
google_analytics: UA-96775017-3
theme: jekyll-theme-cayman
downloads:
  chrome: https://chrome.google.com/webstore/detail/recipe-thing/omonbdfjebcopdfdkiaaajifkaelcohp
  firefox: https://addons.mozilla.org/en-US/firefox/addon/recipecleaner/
